### PR TITLE
add open Player.log option to the launcher

### PR DESCRIPTION
**Pull request by Spirtix**
tested on windows and linux

### CODE REVIEW

**Review by SkySwimmer — CHANGES_REQUESTED** [review]
Id use forward slashes for code readability in the windows-based call but other than its pretty good

**Comment by SkySwimmer** [comment]
Also instead of creating a new instance of UnixSystem to fetch the username, use `System.getProperty("user.name")`, no extra object instantiation needed

**Comment by Spirtix** [comment]
> Id use forward slashes for code readability in the windows-based call but other than its pretty good

done

> Also instead of creating a new instance of UnixSystem to fetch the username, use `System.getProperty("user.name")`, no extra object instantiation needed

reading env variables is sometimes viewed as less secure, but ok

**Comment by SkySwimmer** [comment]
System.getProperty is java properties, not environment, they are assigned by the JVM

**Review by SkySwimmer — APPROVED** [review]

**Pull request merged**
